# Generated by Django 5.0.1 on 2024-01-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='fecha_termino_directiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='rut_directiva',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
