# Generated by Django 5.0.1 on 2024-01-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_organizacion_fecha_termino_directiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='rut_directiva',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
