# Generated by Django 5.0.1 on 2024-01-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_organizacion_rut_directiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='tipo_de_organizacion',
            field=models.CharField(max_length=100),
        ),
    ]
