# Generated by Django 5.0.1 on 2024-01-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_organizacion_rol_municipalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='numero_inscripcion_rc',
            field=models.IntegerField(),
        ),
    ]
